const UPDATE_SHOWINGS = 'UPDATE_SHOWINGS';
const SAVE_SHOWING = 'SAVE_SHOWING';
const INIT_SHOWINGS = 'INIT_SHOWINGS';
const POPULATE_SHOWINGS = 'POPULATE_SHOWINGS';
const APPROVE_SHOWING = 'APPROVE_SHOWING';

export { UPDATE_SHOWINGS, INIT_SHOWINGS, POPULATE_SHOWINGS, SAVE_SHOWING, APPROVE_SHOWING };
